### ISSUE TITLE
json_key authentication not supported

### ISSUE THREAD

**Issue by chris-volley** [GoogleCloudPlatform/gcr-cleaner#101]
I Do the following in a github action. Looks like json_key authentication is not supported. Is there a way around this?

```
 - uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_SVC_ACCOUNT_JSON }}
  - uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo=us-central1-docker.pkg.dev/<myrepo>
            -keep=3
            -tag-filter-all=dev.+$
```
            
gives me the error  
"failed to setup auther: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."
