### ISSUE TITLE
Permission Error: DENIED: Failed to read tags for host 'gcr.io

### ISSUE THREAD

**Issue by ralphotowo** [GoogleCloudPlatform/gcr-cleaner#132]
Hello, 

I have setup Github actions to purge images from a GCR repository as follows. I encounter the following error message after it runs. I have updated the service account with full permissions `roles/owner` and continue to get the same error. I see that someone else encountered the same error and had to include an authentication step, can anyone point me in the right direction here?

> ```failed to list tags for repo gcr.io/webapp-alpha/curl: GET https://gcr.io/v2/project-alpha/curl/tags/list?n=1000: DENIED: Failed to read tags for host 'gcr.io', repository '/v2/project-alpha/curl/tags/list?n=1000'```

Here's my action code:
```
name: 'gcr-cleaner'

on:
  schedule:
    - cron: '0 0 */1 * *'
  push:
  workflow_dispatch:
  
jobs:
  gcr-cleaner:
    runs-on: ubuntu-latest
    steps:
      - name: Login to gcr.io
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_CLEANER_SERVICE_ACCOUNT }}

      - name: Purge untagged images
        uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        env:
          GCRCLEANER_LOG: debug
        with:
          args: >-
            -repo=gcr.io/project-alpha/curl
            -grace=168h
            -keep=10 
            -dry-run

```

**Comment by DavidShefcik** [comment]
One of our actions just ran into this. We ran another action in the same repo that has the same step and it worked. Try running it again?

**Comment by ralphotowo** [comment]
It hasn't worked since day one. And I just tried again without success. 

@DavidShefcik Does my Github action look correct? Are you also running on GCR? What permissions does your service account have?

**Comment by DavidShefcik** [comment]
@ralphotowo I think the way your trying to authenticate with GCR is incorrect. To authenticate with GCR I was using the [setup-glcoud action](https://github.com/google-github-actions/setup-gcloud) like
```yml
... rest of action
- name: Configure Google Cloud SDK
  uses: google-github-actions/setup-gcloud@v0
  with:
    service_account_key: ${{ secrets.GCP_SA_KEY }}
    export_default_credentials: true
```

I then had a step to extract the access token after that
```yml
- name: Get access token from Google Cloud SDK
   id: gcloud-access-token
   run: |
     access_token=$(gcloud auth application-default print-access-token --project <YOUR GCP PROJECT ID HERE>)
     echo "::add-mask::$access_token"
     echo "::set-output name=access_token::$access_token"
```

Finally, my GCR cleaner step looked like
```yml
 - name: Clean out old images
    uses: docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:0.11.1
    with:
      args: >- # https://stackoverflow.com/a/21699210/2367913
        -repo=gcr.io/<your project id>/<your GCR repo name>
        -token=${{ steps.gcloud-access-token.outputs.access_token }}
        -tag-filter-any="^\d+-.*$"
        -keep=5
        -grace=24h
```

For the permissions my service account has `roles/artifactregistry.repoAdmin` permission like the README mentions here - https://github.com/GoogleCloudPlatform/gcr-cleaner#artifact-registry

**Comment by sethvargo** [comment]
Hi there. There's a few things that might be happening here:

1. Are you sure the `GCR_CLEANER_SERVICE_ACCOUNT` GitHub secret exists and is injected into the environment. GitHub does not inject secrets into Pull Requests from forks.

1. Is `GCR_CLEANER_SERVICE_ACCOUNT` an exported JSON service account key in JSON format? If it's base64-encoded, the `username` should be `_json_key_base64` instead of `_json_key`.

1. What are the full GitHub Actions [debug logs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging).

If you've migrated from GCR to GAR, you also need to make sure you have `roles/artifactregistry.repoAdmin` on the given service account.

**Comment by pigoz** [comment]
@ralphotowo took me some time to figure it out as well.

This works for me. You should be able to copy paste it and just change the `env:` section.

```yaml
name: Container Registry Cleanup

on:
  schedule:
    - cron: '0 0 */1 * *' # runs daily
  workflow_dispatch: # allows for manual invocation

env:
  PROJECT_ID: project-123456
  REGISTRY: europe-west1-docker.pkg.dev
  REPOSITORY: europe-west1-docker.pkg.dev/project-123456/repo/service

jobs:
  gcr-cleaner:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Google Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Get access token from Cloud SDK
        id: gcloud_access_token
        run: |
          access_token=$(gcloud auth application-default print-access-token --project ${{ env.PROJECT_ID }})
          echo "::add-mask::$access_token"
          echo "::set-output name=access_token::$access_token"

      - uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo=${{ env.REPOSITORY }}
            -token=${{ steps.gcloud_access_token.outputs.access_token }}
            -keep=5
            -grace=48h
```
